name: macro_builder
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  build: ^2.0.0
  dart_style: ^2.0.0
  source_gen: ^1.0.2
  lints: ^1.0.0
dev_dependencies:
  build_runner: ^2.0.0
dependency_overrides:
  analyzer:
    git:
      ref: fix-source-visitor
      url: https://github.com/jakemac53/sdk.git
      path: pkg/analyzer
  meta:
    git:
      ref: fix-source-visitor
      url: https://github.com/jakemac53/sdk.git
      path: pkg/meta
